### ISSUE TITLE
Circular progress indicator is loaded endlessly after registration email is sent

### ISSUE THREAD

**Issue by abhijithanandan** [tornotron/echno_attendance#23]

**Comment by abinkjohny** [comment]
This is happening because we use `Navigator.pop()` in the "Verification Email Sent..!" Dialog Box

**Comment by abhijithanandan** [comment]
This happens because of the wrong state emitted during the registration event. It is not a problem with `Navigator.pop()`. To resolve the issue, emit `AuthEmailNotVerifiedState`  instead of `AuthNotInitializedState`  during `AuthResitrationEvent` in `AuthBloc`

**Comment by abinkjohny** [comment]
Commit [296ac6c](https://github.com/tornotron/echno_attendance/commit/296ac6cc6dc12aacf8640f919f2f6ec11e9d59b2) has the solution for the issue
